### ISSUE TITLE
【suggestion】more function

### ISSUE THREAD

**Issue by blood789** [Crimix/PermissionLevels#2]
【suggestion】
I want to make an modpack to prohibit players from cheating. can you add more function to your mods?

1.In single player mode, only survival mode can be selected when creating a game, and cheating is forcibly turned off. All command are refused in the game. If it is detected that the player is in non-survival mode, modify NBT to force it to switch to survival mode and turn off cheating.

2.On the server side, delete the op list. No one can become an administrator. If an administrator is detected, delete its administrator privileges.

3.On the server side, whether in the game or the cmd console, refuse to execute all commands. Only the server stop command is allowed.

**Comment by Crimix** [comment]
This sounds like a whole new more inversive mod, the main issue would be not all commands are "bad" and some mods do not work without them.
