### ISSUE TITLE
Permission to make a fabric port

### ISSUE THREAD

**Issue by Foxite** [Crimix/PermissionLevels#3]
I'd like to publish a fabric port of this mod, however since this mod has no open source license (consider adding one), I should ask for permission first.

Also, if you grant permission, what license should I use on my project?

**Comment by Foxite** [comment]
Permission to use the code is no longer necessary, I have already finished writing a mod without referring to your code. However I'm still asking for permission to call it "PermissionLevels-Fabric", if you don't want me to associate our mods then I'll name it something else.

**Comment by Crimix** [comment]
I see no issue in that.

**Comment by Foxite** [comment]
[It's here](https://github.com/Foxite/PermissionLevels-Fabric) if anyone comes here looking for the port.
