### ISSUE TITLE
[Request] Option to enable/disable bypassPlayerLimit

### ISSUE THREAD

**Issue by shinji257** [Crimix/PermissionLevels#4]
It appears in the code you may already reference this but can you make it so that when the command is run it can optionally define if the bypassPlayerLimit option is enabled or not?

**Comment by Crimix** [comment]
I am not quite sure what you are asking for, it is for a way to enable or disable bypassPlayerLimit from in-game using a command?

**Comment by shinji257** [comment]
Correct.

**Comment by ALainxD** [comment]
The Fabric version of the mod ported by a guy from a closed issue here has this feature btw, maybe you could contact them and use their code?

**Comment by Crimix** [comment]
I don't feel the need to look at the fabric port just to provide a optional boolean in a command, I just need the time to implement it

**Comment by ALainxD** [comment]
Sorry I'm not a programmer by myself and only thought it will maybe make your work a bit easier and wanted to let you know about that.

**Comment by Crimix** [comment]
It's alright, thanks anyway for letting me know the port had a feature which I did not have yet

**Comment by stavie131** [comment]
ALain, Shinji and I are all staff on the same network, would a donation push this along?

Edit: Can you also do it on 1.16.5?

**Comment by Crimix** [comment]
I have implemented my version of it for 1.19 as of right now, it will take some time to get it ported back to previous versions

**Comment by shinji257** [comment]
Thank you.  We will wait.

**Comment by shinji257** [comment]
I'm going to add this here as it is a small change.  Can you expand the possible op levels to include level 0?  Not overly documented but it allows players to bypass the player limit without the ability to bypass spawn protection.

https://minecraft.fandom.com/wiki/Permission_level

**Comment by Crimix** [comment]
I can maybe change the new command `bypassPlayerLimit` to not check for if the player is an OP, such that it can be used on non-ops thus making them a level 0 op while they can bypass the player limit

**Comment by shinji257** [comment]
Ahh, I didn't notice you were adding it as a new command.  Yes, that would work then since that is all level 0 gives (afaik).

**Comment by ALainxD** [comment]
Just for Information because it's not documented anywhere in wikis, permission level 0 still gives you the ability to see command/console outputs in the ingame-chat, and it also allowes you to access some mod related OP functions when they didn't check for a permission level. 
(for example Observable still lets you run a profiler and use the teleport feature in there because it doesn't look for permission level, just if the player is OP, and OP with permission level 0 ist still a OP)

For the usecase we have on our servers a server side only mod that simple has the playerlimitbypass function and nothing else would be sweeeet, but that's just a dream.

**Comment by Crimix** [comment]
Based on what ALainxD has said and my own findings, I think it would be better to not go down the undocumented features route and stick with my first implementation to have the lowest level be 1 that supports bypassPlayerLimit.

It sounds like your specific case requires a seperate mod which is totally decoupled from op levels, which is outside the scope of this mod.

Thus I will just be porting what I made for 1.19 without further changes

**Comment by Crimix** [comment]
The current implementation has been backported, I will close this issue now
