### ISSUE TITLE
[Bug] Crash with 1.16.5/1.0.2 on Mixins

### ISSUE THREAD

**Issue by shinji257** [Crimix/PermissionLevels#5]
The new version seems to not work properly giving an error in Mixins with `org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on register could not find any targets matching 'register(Lcom/mojang/brigadier/CommandDispatcher;)V' in net.minecraft.command.impl.OpCommand. No refMap loaded. [PREINJECT Applicator Phase -> permissionlevels.mixins.json:OpCommandMixin -> Prepare Injections ->  -> handler$zza000$register(Lcom/mojang/brigadier/CommandDispatcher;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]`

Gist: https://gist.github.com/shinji257/0b4904d953bd318d340a3ecc2250f259

Tested the previous version (1.0.1) and it loaded fine.

EDIT: Just wanted to add that this was discovered when we were using it with modpacks but to ensure that it isn't another mod causing this the crash log above is from running the latest forge for 1.16.5 and no other mods at all.

**Comment by Crimix** [comment]
Thank you, it seems like the 1.16.5 version did not compile correctly as the mixin refmap was missing.
Fixed in 1.0.3
